apiVersion: v1
kind: Service
metadata:
  name: csro-gym-tool-db
spec:
  ports:
  - port: 3306
  selector:
    app: csro-gym-tool-mysql
  clusterIP: None
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: csro-mysql
spec:
  selector:
    matchLabels:
      app: csro-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: csro-mysql
    spec:
      containers:
      - image: mysql:5.6
        name: csro-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: daigual_nolausa
        - name: MYSQL_DATABASE
          value: daigual_nolausa
        ports:
        - containerPort: 3306
          name: csro-mysql
        volumeMounts:
        - name: csro-gym-tool-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: csro-gym-tool-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: csro-gym-tool-mysql-pvc
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csro-gym-tool-mysql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: csro-gym-tool-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    