apiVersion: v1
kind: Service
metadata:
  name: games-info-server-service
  labels:
    app: games-info-server-service
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: games-info-port
  selector:
    app: games-info-server-service
---
apiVersion: v1
kind: Service
metadata:
  name: games-info-mail-service
  labels:
    app: carlos.sanchezro
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    name: games-info-mail-port
  selector:
    app: games-info-mail-service
