apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: csro-gym-tool-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:  
  rules:
  - host: gym-tool.minikube.io
    http:
      paths:
      - path: /home/
        backend:
          serviceName: csro-gym-tool
          servicePort: 8080
